### PR TITLE
[ENH] Impemented validation for output JSON

### LINKED ISSUE #597: Make sure we create valid .json

### PR DESCRIPTION
**Pull request by rmanaem**
Closes #597 

## Checklist

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see https://neurobagel.org/contributing/pull_requests for more info)_
- [x] PR links to GitHub issue with mention `Closes #XXXX`
- [x] Tests pass
- [x] Checks pass

For new features:
- [x] Tests have been added

For bug fixes:
- [x] There is at least one test that would fail under the original bug conditions.

### CODE REVIEW

**Comment by surchs** [comment]
@rmanaem I think one reason the id selectors were so brittle might have to do that you ran the e2e locally off of `npm runn dev` but on the CI they are running off of the generated app (I believe).

**Review by surchs — APPROVED** [review]
:cook: with the fixes to the download page test

when you merge, make sure that these two changes appear on the top of the itemized changes in the PR description.

**Comment by alyssadai** [comment]
@rmanaem please also update the label for the "other" sex to read "Indeterminate sex" instead, to match the [actual SNOMED term](https://bioportal.bioontology.org/ontologies/SNOMEDCT?p=classes&conceptid=32570681000036106). 🙂

**Comment by rmanaem** [comment]
> I think one reason the id selectors were so brittle might have to do that you ran the e2e locally off of npm runn dev but on the CI they are running off of the generated app (I believe).

@surchs I see, so you think the generated IDs would be different when app is started using `npm run generate` as opposed to `npm run dev`. That would explain the discrepancies.

**Pull request merged**
