### PR TITLE
Connecting up Phase 1 Refactor Work to Allow Passage Through to Categorization Page

### PR DESCRIPTION
**Pull request by jarmoza**
This PR represents a kind of glue between the two phases of our store refactor for the annotation tool. The overall goal was to produce a version of the tool that is working up to the categorization page.

As such there are a number of varied tasks which are described in the issues below. Generally, they cover:

1. The addition of store fields/methods that were not added during the initial refactor for various reasons
2. Nominal refactor changes like name changes
3. Ensuring proper initialization of store fields and loading of the data table/data dictionary
4. Further adapting navigation/page accessibility code
5. Updating the pages and their components as needed to ensure the new workflow functions (upload table -> upload dictionary (optional, but not before data table upload) -> go to categorization page, etc.)
6. Components functioning at least to the point where they don't break the app when loaded on their respective page.

The specific issues covered are listed in #251, but the relevant ones are re-listed below for convenience.

- [x] #300 
- [x] #307
- [x] #308
- [x] #313
- [x] #314
- [x] #315

There remain several bugs, the consequence of which mostly do not interfere with the general goal of a working app up to the categorization page. They are:

- [ ] #316
- [x] #317
- [x] #320

### CODE REVIEW

**Comment by jarmoza** [comment]
@surchs Standby for check/fix on failed component test(s)

**Comment by jarmoza** [comment]
@surchs Could you put an eye on https://github.com/neurobagel/annotation_tool/blob/jarmoza-308/cypress/component/category-select-table.cy.js ? I've been scratching my head as to why this is failing.

**Comment by surchs** [comment]
Glad you resolved the issue @jarmoza, sorry it took me so long to check it out. Would you mind pushing your fix?

**Comment by jarmoza** [comment]
This PR will be closed without merge all tasks in #251 for phase 1 refactor are complete.

**Comment by jarmoza** [comment]
I am closing this now that the Phase 1 refactor work has been completed by PRs separating (and improving upon) this one - last one is #330 for reference.

**Pull request closed without merging**
